Parameters:
  DynamoDBArn:
    Type: String
    Description: Arn of the DynamoDB Table for Vanity Numbers

Resources:
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole
  DynamoDBLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed Policy for the lambda role to access dynamoDB
      ManagedPolicyName: DynamoDBLambdaAccessPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !Ref DynamoDBArn
      Roles:
        - !Ref LambdaFunctionRole
  VanityNumbersLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: VanityNumbers
      Code:
        ImageUri: 859530432683.dkr.ecr.us-east-1.amazonaws.com/vanity-numbers:latest
      PackageType: Image
      Description: Invoke the Vanity Numbers Lambda
      Role: !GetAtt 'LambdaFunctionRole.Arn'
      Environment:
        Variables:
          NLTK_DATA: /var/task/nltk_data
          DB_TABLE: callers
Outputs:
  VanityNumbersLambda:
    Value: !GetAtt VanityNumbersLambda.Arn