AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ConnectArn:
    Type: String
    Description: Enter the Connect Instance Arn
    
Resources: 
  CallersDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "callers"
      AttributeDefinitions:
        - AttributeName: "callerPhone"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "callerPhone"
          KeyType: "HASH"
      BillingMode: "PROVISIONED"
      ProvisionedThroughput: 
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
  VanityNumberContactSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: contactFlow/vanityNumber.yaml
      Parameters:
        VanityLambdaArn: !GetAtt LambdasSubStack.Outputs.VanityNumbersLambda
        ConnectArn: !Ref ConnectArn
  LambdasSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: functions/lambdas.yaml
      Parameters:
        DynamoDBArn: !GetAtt CallersDynamoDB.Arn
